name: hikkingapp
description: "A new Flutter project."


publish_to: 'none' 








version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  flutter_svg: "^2.0.9"
  flutter_screenutil: ^5.9.0
  firebase_core: ^3.13.1
  firebase_auth: 
  cloud_firestore: ^5.6.8
  dropdown_button2: ^2.3.9
  provider: ^6.1.5
  permission_handler: ^11.0.0
  


  #map
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_location_marker: ^10.0.2
  geolocator: ^13.0.4
  location: ^8.0.1
  http: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:
  assets:
    - assets/images/ 
    
    


  
  
  # fonts:
  #   - family: popinbold
  #     fonts:
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #   - family: popin
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #   - family: popinsemibold
  #     fonts:
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #   - family: popinmedium
  #     fonts:
  #       - asset: assets/fonts/Poppins-Medium.ttf
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
