// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDri_K4gM68P3_xNYfWnm7ofjvodNNZvsM',
    appId: '1:1057553484135:web:4753a4f4cbbe046afb07c2',
    messagingSenderId: '1057553484135',
    projectId: 'hikkingapp',
    authDomain: 'hikkingapp.firebaseapp.com',
    storageBucket: 'hikkingapp.firebasestorage.app',
    measurementId: 'G-XNVK4G4KE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1uVY4o6o-bZCkyOaDKPIbUZXtIJkbZ4',
    appId: '1:1057553484135:android:590e5fc41456d475fb07c2',
    messagingSenderId: '1057553484135',
    projectId: 'hikkingapp',
    storageBucket: 'hikkingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP53gy1opyyvUEQxGeaXvYDddTdKSfxtU',
    appId: '1:1057553484135:ios:2c63d82ed5833761fb07c2',
    messagingSenderId: '1057553484135',
    projectId: 'hikkingapp',
    storageBucket: 'hikkingapp.firebasestorage.app',
    iosBundleId: 'com.example.hikkingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP53gy1opyyvUEQxGeaXvYDddTdKSfxtU',
    appId: '1:1057553484135:ios:2c63d82ed5833761fb07c2',
    messagingSenderId: '1057553484135',
    projectId: 'hikkingapp',
    storageBucket: 'hikkingapp.firebasestorage.app',
    iosBundleId: 'com.example.hikkingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDri_K4gM68P3_xNYfWnm7ofjvodNNZvsM',
    appId: '1:1057553484135:web:72d2212d87469df3fb07c2',
    messagingSenderId: '1057553484135',
    projectId: 'hikkingapp',
    authDomain: 'hikkingapp.firebaseapp.com',
    storageBucket: 'hikkingapp.firebasestorage.app',
    measurementId: 'G-RLXT40307F',
  );
}
